descriptor_extension: yml
package:
  description: Project for the development of VPN + TOR + vFW service of the PSA pilot.
  maintainer: SONATA
  name: sonata-psa-vpn-tor-vfw
  vendor: eu.sonata-nfv
  version: '0.2'
version: '0.5'
