---
# tasks file for docker-openvpn

- name: start OpenVPN as a Docker containers
  docker_container:
    name: snort
    image: kylemanna/openvpn
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ docker_network_name }}"
        aliases:
          - vpsa-mgmt

      - name: "{{ vl_vpsa_user }}"
        aliases:
          - vpsa-user

      - name: "{{ vl_vpn_fw }}"
        aliases:
          - vpsa-vpn-fw
        links:
          - vpsa-vpn-fw:vpn-fw

    restart_policy: "unless-stopped"
    volumes:
      - /var/log/sonata/openvpn:/var/log/openvpn
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

