descriptor_extension: yml
package:
  description: Project for the testing of TOR FSM
  maintainer: Luis Conceicao, UBIWHERE, lconceicao@ubiwhere.com
  name: sonata-psa-tor_css-fsm
  vendor: ubiwhere
  version: '0.1'
version: '0.5'
