---
# defaults file for vcc

sp_user: sonata
sp_pass: "$1$SRc2ws2Z$rSdCC/UKiatagNdfsTVuf0"

nbofvms: 1
pop: alabs
proj: demo
distro: xenial

# SONATA 5G NFV SP development/latest version
sp_ver: dev
domain_name: sonata-nfv.eu
sp_fqdn: "sp.{{ pop }}.sonata-nfv.eu"

