---
# handlers file for squid

- name: reload firewalld
  shell: firewall-cmd --reload
  when: ansible_distribution == "CentOS"

- name: reload ufw
  service: name=ufw state=reloaded
  when: ansible_distribution == "Ubuntu"

