descriptor_extension: yml
package:
  description: SONATA PSA
  maintainer: Luis Conceicao, UBIWHERE, lconceicao@ubiwhere.com
  name: "sonata-psa"
  vendor: "eu.sonata-nfv"
  version: "0.9"
version: '0.5'
