- hosts: "{{ plat }}"
  become: true
  connection: ssh
  vars:
    localhome: "{{ lookup('env','PWD') }}"

  pre_tasks:

    - local_action: shell date +'%F %T'
      register: timestamp

    - debug:
        msg: "{{ timestamp.stdout }}"

  roles:
    - nginx
