---
# tasks file for squid

- include: "{{ ansible_distribution_release }}.yml"

- name: installing SQUID proxy server
  package:
    name: squid
    state: latest

# preserve original config file
- fetch:
    src: /etc/squid/squid.conf
    dest: /tmp/squid.conf
    flat: yes
- copy:
    src: /tmp/squid.conf
    dest: /etc/squid/squid.conf.ORIG
    owner: root
    group: root
    mode: 0640

- name: setting your specific configuration
  copy:
    remote_src: false
    src: "{{ lookup('env','PWD') }}/roles/squid/files/squid.conf"
    dest: /etc/squid/squid.conf

- name: start SQUID service
  service: name=squid state=started enabled=yes

