
#- name: Docker User Defined Network (ENDUSER)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.2.0/24 --gateway=172.22.2.1 \
#--ip-range=172.22.2.128/25 "{{ vl_enduser }}"'

#- name: Docker User Defined Network (PRX-IDS)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.3.0/24 --gateway=172.22.3.1 \
#--ip-range=172.22.3.128/25 "{{ vl_prx_ids }}"'

#- name: Docker User Defined Network (PRX-LDAP)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.4.0/24 --gateway=172.22.4.1 \
#--ip-range=172.22.4.128/25 "{{ vl_prx_ldap }}"'

#- name: Docker User Defined Network (PRX-ADDBLK)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.5.0/24 --gateway=172.22.5.1 \
#--ip-range=172.22.5.128/25 "{{ vl_prx_addblk }}"'

#- name: Docker User Defined Network (ADDBLK-IDS)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.6.0/24 --gateway=172.22.6.1 \
#--ip-range=172.22.6.128/25 "{{ vl_addblk_ids }}"'

#- name: Docker User Defined Network (IDS-FW)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.22.7.0/24 --gateway=172.22.7.1 \
#--ip-range=172.22.7.128/25 "{{ vl_ids_fw }}"'

