descriptor_extension: yml
package:
  description: Project for the development of VPN + fsm service
  maintainer: Luis Conceicao, UBIWHERE, lconceicao@ubiwhere.com
  name: sonata-psa-vpn-fsm
  vendor: ubiwhere
  version: '0.1'
version: '0.5'
