# Pre-requirements
- name: install CentOS 7 depedency libraries and tools
  yum: name={{ item }}
  with_items:
    - wget
    - gcc
    - pcre-static
    - pcre-devel
    - openssl-devel

- file:
    path: /tmp/haproxy
    state: directory
    mode: 0755

- name: download HA Proxy tarball
  unarchive:
    src: http://www.haproxy.org/download/1.7/src/haproxy-1.7.2.tar.gz
    dest: /tmp
    remote_src: true

- name: install HAProxy
  shell: cd /tmp/haproxy-1.7.2 && make TARGET=linux2628 USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 && make install

- command: cp /usr/local/sbin/haproxy /usr/sbin/
- command: cp /tmp/haproxy-1.7.2/examples/haproxy.init /etc/init.d/haproxy

- file:
    path: /etc/init.d/haproxy
    #state: touch
    mode: "u=rw,g=r,o=r"

- group:
    name: haproxy
    state: present

- user:
    name: haproxy
    shell: /usr/sbin/nologin
    groups: haproxy
    append: yes
    comment: "HA PRX"

- file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - /etc/haproxy
    - /run/haproxy
    - /var/lib/haproxy

- file:
    path: '{{ item }}'
    state: touch
    mode: 'u=rw,g=r,o=r'
  with_items:
    - /var/lib/haproxy/stats

- name: HAProxy configuration file 
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=haproxy group=haproxy mode=0644

- name: upload shared libraries
  command: ldconfig


# Open FW ports
- yum: name=python-firewall state=present
- name: open SVC ports
  firewalld:
    port: "{{ svc_port }}/tcp"
    permanent: true
    state: enabled
  notify: reload firewalld

# provide feedback on the installed version 

- command: haproxy -v
  register: haproxy_ver
- debug: msg={{ haproxy_ver.stdout }}
